src/Entity/Cours.php
<?php

namespace App\Entity;

use Assert\Callback;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $max_eleves = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_debut = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_fin = null;

    #[ORM\Column(length: 20)]
    private ?string $date_hebdomadaire = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    

    #[ORM\OneToMany(mappedBy: 'cours', targetEntity: Inscrit::class)]
    private Collection $inscrits;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $utilisateur = null;

    #[ORM\OneToMany(mappedBy: 'cours_id', targetEntity: Seances::class)]
    private Collection $seances;

    public function __construct()
    {
        $this->inscrits = new ArrayCollection();
        $this->seances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMaxEleves(): ?float
    {
        return $this->max_eleves;
    }

    public function setMaxEleves(float $max_eleves): self
    {
        $this->max_eleves = $max_eleves;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heure_debut;
    }

    public function setHeureDebut(\DateTimeInterface $heure_debut): self
    {
        $this->heure_debut = $heure_debut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heure_fin;
    }

    public function setHeureFin(\DateTimeInterface $heure_fin): self
    {
        $this->heure_fin = $heure_fin;

        return $this;
    }

    public function getDateHebdomadaire(): ?string
    {
        return $this->date_hebdomadaire;
    }

    public function setDateHebdomadaire(string $date_hebdomadaire): self
    {
        $this->date_hebdomadaire = $date_hebdomadaire;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, Presence>
     */
    

    /**
     * @return Collection<int, Inscrit>
     */
    public function getInscrits(): Collection
    {
        return $this->inscrits;
    }

    public function addInscrit(Inscrit $inscrit): self
    {
        if (!$this->inscrits->contains($inscrit)) {
            $this->inscrits->add($inscrit);
            $inscrit->setCours($this);
        }

        return $this;
    }

    public function removeInscrit(Inscrit $inscrit): self
    {
        if ($this->inscrits->removeElement($inscrit)) {
            // set the owning side to null (unless already changed)
            if ($inscrit->getCours() === $this) {
                $inscrit->setCours(null);
            }
        }

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }
    public function getUtilisateurNom(): string
{
    return $this->utilisateur ? $this->utilisateur->getNomUtilisateur() : '';
}

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }


    /**
 * @param array $seances
 */
public function setSeances(array $seances): void
{
    $this->seances = new ArrayCollection($seances);
    foreach ($seances as $seance) {
        $seance->setCoursId($this);
    }
}

    /**
     * @return Collection<int, Seances>
     */
    public function getSeances(): Collection
    {
        return $this->seances;
    }

    public function addSeance(Seances $seance): self
    {
        if (!$this->seances->contains($seance)) {
            $this->seances->add($seance);
            $seance->setCoursId($this);
        }

        return $this;
    }

    public function removeSeance(Seances $seance): self
    {
        if ($this->seances->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getCoursId() === $this) {
                $seance->setCoursId(null);
            }
        }

        return $this;
    }
}

src/Entity/Presence.php
<?php

namespace App\Entity;

use App\Repository\PresenceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PresenceRepository::class)]
class Presence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    

    #[ORM\Column]
    private ?int $validation_presence = null;

    #[ORM\ManyToOne(inversedBy: 'presences')]
    private ?Eleve $eleve = null;
   
    #[ORM\ManyToOne(inversedBy: 'presences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Seances $seances = null;

    public function getId(): ?int
    {
        return $this->id;
    }
   
    public function getValidationPresence(): ?int
    {
        return $this->validation_presence;
    }

    public function setValidationPresence(int $validation_presence): self
    {
        $this->validation_presence = $validation_presence;

        return $this;
    }

    public function getEleve(): ?Eleve
    {
        return $this->eleve;
    }

    public function setEleve(?Eleve $eleve): self
    {
        $this->eleve = $eleve;

        return $this;
    }
   
    public function getSeances(): ?Seances
    {
        return $this->seances;
    }

    public function setSeances(?Seances $seances): self
    {
        $this->seances = $seances;

        return $this;
    }

    //fonctions pour afficher les noms et prénoms des élèves inscrit aux cours sur les pages twig 
    public function getCoursNomEleve(): string
    {
    return $this->eleve ? $this->eleve->getNomEleve() : '';
    }

    public function getCoursPrenomEleve(): string
    {
    return $this->eleve ? $this->eleve->getPrenomEleve() : '';
    } 

    //Fonction pour chercher la date de la séance
    public function getDateSeance(): ?\DateTimeInterface
    {
        return $this->seances ? $this->seances->getDate() : '';
    }
}

src/Form/PresenceType.php
<?php

namespace App\Form;

use App\Entity\Eleve;
use App\Entity\Seances;
use App\Entity\Presence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PresenceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder            
            ->add('validation_presence', ChoiceType::class, [
                'choices' => [
                    'absent' => 0,
                    'présent' => 1,
                    'absence justifiée' => 2
                ],
                'attr'=>[
                    'class'=> 'btn btn-outline-secondary nav-link dropdown-toggle mb-4 mt-1'
                ]
            ])
            ->add('eleve', EntityType::class, [
                'class' => Eleve::class,
                // On utilise le choice label getNomComplet() qui a été créer directement dans l'entité Eleve
                'choice_label' => 'nom_complet',
                'expanded' => true,
                'multiple' => false,
            ])
            //Si on veut modifier la séance
            // ->add('seances', EntityType::class, [
            //     'class' => Seances::class,
            //     'choice_label' => 'id',
            // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Presence::class,
        ]);
    }
}

src/Controller/PresenceController.php
<?php

namespace App\Controller;

use App\Entity\Presence;
use App\Form\PresenceType;
use App\Repository\CoursRepository;
use App\Repository\SeancesRepository;
use App\Repository\PresenceRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/presence')]
#[IsGranted('ROLE_USER')]
class PresenceController extends AbstractController
{
    /**
     * Fonction pour afficher la liste des cours
     *
     * @param CoursRepository $coursRepository
     * @return Response
     */
    #[Route('/', name: 'app_presence_index', methods: ['GET'])]
    public function index(CoursRepository $coursRepository): Response
    {
        return $this->render('presence/listeCours.html.twig', [
            'cours' => $coursRepository->findAll(),
        ]);
    }
    
    /**
     * fonction pour afficher la liste des séances d'un cours en particulier
     *
     * @param PresenceRepository $presenceRepository
     * @return Response
     */
    
    #[Route('/list/{id}', name: 'app_cours/seances_list', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function indexSeance(int $id, SeancesRepository $seancesRepository): Response
    {
        //On veut les séances du cours dont l'id est dans l'url
        $seances = $seancesRepository->findBy(['cours_id' => $id]);       

        //on envoie le nouveau tableau au front
        return $this->render('presence/listeSeances.html.twig', [
            'seances' => $seances,
        ]);
    }

    /**
     * fonction pour afficher la liste des présences d'une séance en particuliers
     */
    #[Route('/seances/{id}', name: 'app_seances/presences_list', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function indexPresence(int $id, PresenceRepository $presenceRepository): Response
    {
        //On veut les séances du cours dont l'id est dans l'url
        $presences = $presenceRepository->findBy(['seances' => $id]);       

        //on envoie le nouveau tableau au front
        return $this->render('presence/listPresences.html.twig', [
            'presences' => $presences,
        ]);
    }

    //  /**
    //  * fonction pour afficher la liste des inscrits à un cours particulier
    //  *
    //  * @param PresenceRepository $presenceRepository
    //  * @return Response
    //  */
    
    //  #[Route('/list/{id}', name: 'app_presence_list', methods: ['GET'])]
    //  #[IsGranted('ROLE_USER')]
    //  public function indexPresence(PresenceRepository $presenceRepository, int $id, SeancesRepository $seancesRepository): Response
    //  {
    //      //On veut les séances du cours dont l'id est dans l'url
    //      $seances = $seancesRepository->findBy(['cours_id' => $id]);
 
    //      //On va chercher les présences parmis cette sélection de séances
    //      $presences = [];
    //      foreach ($seances as $seance) {
    //          $seancePresences = $presenceRepository->findBy(['seances' => $seance->getId()]);
    //          $presences = array_merge($presences, $seancePresences);
    //      }
 
    //      //on envoie le nouveau tableau au front
    //      return $this->render('presence/index.html.twig', [
    //          'presences' => $presences,
    //      ]);
    //  }

    // #[Route('/new', name: 'app_presence_new', methods: ['GET', 'POST'])]
    // public function new(Request $request, PresenceRepository $presenceRepository): Response
    // {
    //     $presence = new Presence();
    //     $form = $this->createForm(PresenceType::class, $presence);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $presenceRepository->save($presence, true);

    //         return $this->redirectToRoute('app_presence_index', [], Response::HTTP_SEE_OTHER);
    //     }

    //     return $this->renderForm('presence/new.html.twig', [
    //         'presence' => $presence,
    //         'form' => $form,
    //     ]);
    // }

    // /**
    //  * Fonction pour voir un objet présence
    //  */
    // #[Route('/{id}', name: 'app_presence_show', methods: ['GET'])]
    // public function show(Presence $presence): Response
    // {
    //     return $this->render('presence/show.html.twig', [
    //         'presence' => $presence,
    //     ]);
    // }

    /**
     * Fonction pour Modifier un objet présence
     */
    #[Route('/{id}/edit', name: 'app_presence_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Presence $presence, PresenceRepository $presenceRepository): Response
    {
        //idSeance correspond à l'id de la séance à laquel l'objet présence est associé, utile pour rediriger
        $idSeance = $presence->getSeances()->getId();

        $form = $this->createForm(PresenceType::class, $presence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $presenceRepository->save($presence, true);

            return $this->redirectToRoute('app_seances/presences_list', ['id'=>$idSeance], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('presence/edit.html.twig', [
            'presence' => $presence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_presence_delete', methods: ['POST'])]
    #[IsGranted('ROLE_USER')]
    public function delete(Request $request, Presence $presence, PresenceRepository $presenceRepository): Response
    {

        //idSeance correspond à l'id de la séance à laquel l'objet présence est associé, utile pour rediriger
        $idSeance = $presence->getSeances()->getId();

        if ($this->isCsrfTokenValid('delete'.$presence->getId(), $request->request->get('_token'))) {
            $presenceRepository->remove($presence, true);
        }

        return $this->redirectToRoute('app_seances/presences_list', ['id'=>$idSeance], Response::HTTP_SEE_OTHER);
    }
}

templates/presence/_delete_form.html.twig
<form method="post" action="{{ path('app_presence_delete', {'id': presence.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir enlever cet élève du cours?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ presence.id) }}">
    <button class="btn btn-warning mt-2">Supprimer</button>
</form>

templates/presence/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-primary mt-4">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/presence/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualiser la présence de l'élève
{% endblock %}

{% block body %}

	{# titre #}
	<div class="d-flex justify-content-center text-center row px-5 mx-1">
		<h1 class="mt-3">Actualiser la présence de l'élève</h1>
	</div>

	{# formulaire #}
	<div class="mx-3">
		<p class="mx-2">Actuellement
			{{ presence.coursPrenomEleve }}
			{{ presence.coursNomEleve }}
		</p>
		<div class="d-flex mx-2">
			{{ include('presence/_form.html.twig', {'button_label': 'Modifier'}) }}
		</div>

		{# Bouton de retour #}
		<div class="mt-5 d-flex ">
			<a class="btn btn-primary mt-2 mx-2" href="{{ path('app_presence_index') }}">Retour à la liste des cours</a>

            {{ include('presence/_delete_form.html.twig') }}
		</div>

		
	</div>
{% endblock %}

templates/presence/listPresences.html.twig
{% extends 'base.html.twig' %}

{% block title %}Presence de la seance{% endblock %}

{% block body %}
<div class="d-flex justify-content-center text-center row px-5  mx-1">
        {% for presence in presences %}
		<h1 class="mt-3">Presences de la séance du {{ presence.DateSeance|date('d-m-Y') }}</h1>
        {% endfor %}
		<div class="p-5">
    

    <table class="table table-striped table-dark" id="dataTable">
        <thead>
            <tr>
                <th class="bg-primary">Nom et Prénom</th> 
                <th class="bg-primary">statut</th>             
                <th class="bg-primary">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for presence in presences %}
            <tr>
                <td>{{presence.coursNomEleve}} {{presence.coursPrenomEleve}}</td>
                <td>
                    {% if presence.validationPresence  == 1 %}
                        présent
                    {% elseif presence.validationPresence  == 2 %}
                        absence justifiée
                    {% else %}
                        absent 
                    {% endif %}
                    
                    </td>              
                <td>
                    {# <a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_presence_show', {'id': presence.id}) }}">Voir</a> #}
                    <a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_presence_edit', {'id': presence.id}) }}">Modifier</a> 
                </td>  
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Pas d'inscription à ce cours enregistré</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

  </div>
</div>  

<div class="w-25 d-flex justify-content-center order-2">
        <a class="btn btn-outline-primary mt-2" href="{{ path('app_presence_index') }}">Retour à la liste des cours</a>
    </div>

    
{% endblock %}

templates/presence/listeCours.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des cours (gestion des présences)
{% endblock %}

{% block body %}
	<div class="d-flex justify-content-center text-center row px-5 mx-1">
		<h1 class="mt-3">Liste des Cours</h1>
		<h4>(gestion des présences)</h4>
		<div class="p-5">
			<table class="table table-striped table-dark" id='dataTable'>
				<thead>
					<tr>
						{# <th class="bg-primary">Id</th> #}
						<th class="bg-primary">Libelle</th>
						<th class="bg-primary">Nombre max d'élèves</th>
						<th class="bg-primary">Description</th>						
						<th class="bg-primary">Heure du début</th>
						<th class="bg-primary">Heure de fin</th>
						<th class="bg-primary">Date hebdomadaire</th>
						<th class="bg-primary">date 1e session</th>
						<th class="bg-primary">date dernière session</th>
						<th class="bg-primary">professeur</th>
						<th class="bg-primary">Actions</th>						
					</tr>
				</thead>
				<tbody>
					{% for cour in cours %}

						{% if is_granted('ROLE_ADMIN') or (app.user.getId()  == cour.utilisateur.id) %}
						<tr>
							{# <td>{{ cour.id }}</td> #}
							<td>{{ cour.libelle }}</td>
							<td>{{ cour.maxEleves }}</td>
							<td>{{ cour.description }}</td>										
				
							<td>{{ cour.heureDebut ? cour.heureDebut|date('H:i') : '' }}</td>
							<td>{{ cour.heureFin ? cour.heureFin|date('H:i') : '' }}</td>
							<td>
								{% if cour.dateHebdomadaire == 0 %}
									dimanche
								{% elseif cour.dateHebdomadaire == 1 %}
									lundi
								{% elseif cour.dateHebdomadaire == 2 %}
									mardi
								{% elseif cour.dateHebdomadaire == 3 %}
									mercredi	
								{% elseif cour.dateHebdomadaire == 4 %}
									jeudi	
								{% elseif cour.dateHebdomadaire == 5 %}
									vendredi
								{% elseif cour.dateHebdomadaire == 6 %}
									samedi
								{% endif %} 
							</td>
							<td>{{ cour.dateDebut ? cour.dateDebut|date('d-m-Y') : '' }}</td>
							<td>{{ cour.dateFin ? cour.dateFin|date('d-m-Y') : '' }}</td>
							<td>{{ cour.utilisateurNom }}</td>
							<td style="width: 13%;">
								<a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_cours/seances_list', {'id': cour.id}) }}">Voir</a>
								{# <a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_inscrit_new', {'id': cour.id}) }}">Inscrire</a> #}
							</td>
						</tr>
						{% endif %}
					{% else %}
						<tr>
							<td colspan="10">Pas de cours enregistrés</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>


	{# <div class="w-25 order-2"></div>
	<div class="w-25 order-1"></div> #}
</div>{% endblock %}

templates/presence/listeSeances.html.twig
{% extends 'base.html.twig' %}

{% block title %}Seances du cours{% endblock %}

{% block body %}
<div class="d-flex justify-content-center text-center row px-5  mx-1">
		<h1 class="mt-3">Séances du cours</h1>
		<div class="p-5">
    

    <table class="table table-striped table-dark" id="dataTable">
        <thead>
            <tr>
                <th class="bg-primary">libelle</th>                
                <th class="bg-primary">date</th>
                <th class="bg-primary">heure du début</th>
                <th class="bg-primary">heure de fin</th>
                <th class="bg-primary">actions</th>                
            </tr>
        </thead>
        <tbody>
        {% for seance in seances %}
            <tr>
                <td>{{ seance.libelle }}</td>               
                <td>{{ seance.date|date('d-m-Y')}}</td>
                <td>{{ seance.heureDebut|date('H:i')}}</td> 
                <td>{{ seance.heureFin|date('H:i')}}</td>  
                
                  <td>
                    <a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_seances/presences_list', {'id': seance.id}) }}">Voir</a>                    
                </td> 
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Pas d'inscription à ce cours enregistré</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="w-25 d-flex justify-content-center order-2">
        <a class="btn btn-outline-primary mt-2" href="{{ path('app_presence_index') }}">Retour à la liste des cours</a>
    </div>

  </div>
</div>  

    {# <a href="{{ path('app_presence_new') }}">Create new</a> #}
{% endblock %}

templates/presence/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Presence{% endblock %}

{% block body %}
    <h1>Create new Presence</h1>

    {{ include('presence/_form.html.twig') }}

    <a href="{{ path('app_presence_index') }}">back to list</a>
{% endblock %}

templates/presence/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Presence{% endblock %}

{% block body %}
    <h1>Presence</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ presence.id }}</td>
            </tr>
            <tr>
                <th>Date_cours</th>
                <td>{{ presence.dateCours ? presence.dateCours|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Validation_presence</th>
                <td>{{ presence.validationPresence }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_presence_index') }}">back to list</a>

    <a href="{{ path('app_presence_edit', {'id': presence.id}) }}">edit</a>

    {{ include('presence/_delete_form.html.twig') }}
{% endblock %}